{
 "title": "DS",
 "time": { "from": "2019-03-15T16:29:18.150Z", "to": "2019-03-15T16:31:24.937Z" },
 "panels": [
  {
   "title": "sandbox commit time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(dshost_commit_duration_s_bucket[10s])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Panel sandbox recycle time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(dshost_recycle_duration_s_bucket[10s])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "requests duration bucket",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(dshost_requests_duration_s_bucket[10s])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Sandbox Statuses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dshost_sandbox_status_counts", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "jifffies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"ds-host\"}[2s])"
    }
   ]
  },
  {
   "title": "reqs per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dshost_requests_duration_s_count[2s])"
    }
   ]
  }
 ]
}