// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/teleclimber/DropServer/cmd/ds-host/testmocks (interfaces: UsersV0)

// Package testmocks is a generated GoMock package.
package testmocks

import (
	gomock "github.com/golang/mock/gomock"
	domain "github.com/teleclimber/DropServer/cmd/ds-host/domain"
	reflect "reflect"
)

// MockUsersV0 is a mock of UsersV0 interface
type MockUsersV0 struct {
	ctrl     *gomock.Controller
	recorder *MockUsersV0MockRecorder
}

// MockUsersV0MockRecorder is the mock recorder for MockUsersV0
type MockUsersV0MockRecorder struct {
	mock *MockUsersV0
}

// NewMockUsersV0 creates a new mock instance
func NewMockUsersV0(ctrl *gomock.Controller) *MockUsersV0 {
	mock := &MockUsersV0{ctrl: ctrl}
	mock.recorder = &MockUsersV0MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUsersV0) EXPECT() *MockUsersV0MockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockUsersV0) Create(arg0 domain.AppspaceID, arg1, arg2 string) (domain.ProxyID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(domain.ProxyID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockUsersV0MockRecorder) Create(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUsersV0)(nil).Create), arg0, arg1, arg2)
}

// Delete mocks base method
func (m *MockUsersV0) Delete(arg0 domain.AppspaceID, arg1 domain.ProxyID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockUsersV0MockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUsersV0)(nil).Delete), arg0, arg1)
}

// Get mocks base method
func (m *MockUsersV0) Get(arg0 domain.AppspaceID, arg1 domain.ProxyID) (domain.AppspaceUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(domain.AppspaceUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockUsersV0MockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUsersV0)(nil).Get), arg0, arg1)
}

// GetAll mocks base method
func (m *MockUsersV0) GetAll(arg0 domain.AppspaceID) ([]domain.AppspaceUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0)
	ret0, _ := ret[0].([]domain.AppspaceUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll
func (mr *MockUsersV0MockRecorder) GetAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockUsersV0)(nil).GetAll), arg0)
}

// GetByDropID mocks base method
func (m *MockUsersV0) GetByDropID(arg0 domain.AppspaceID, arg1 string) (domain.AppspaceUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDropID", arg0, arg1)
	ret0, _ := ret[0].(domain.AppspaceUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDropID indicates an expected call of GetByDropID
func (mr *MockUsersV0MockRecorder) GetByDropID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDropID", reflect.TypeOf((*MockUsersV0)(nil).GetByDropID), arg0, arg1)
}

// UpdateMeta mocks base method
func (m *MockUsersV0) UpdateMeta(arg0 domain.AppspaceID, arg1 domain.ProxyID, arg2, arg3 string, arg4 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMeta", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMeta indicates an expected call of UpdateMeta
func (mr *MockUsersV0MockRecorder) UpdateMeta(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMeta", reflect.TypeOf((*MockUsersV0)(nil).UpdateMeta), arg0, arg1, arg2, arg3, arg4)
}
