// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/teleclimber/DropServer/cmd/ds-host/testmocks (interfaces: ManageUsers)

// Package testmocks is a generated GoMock package.
package testmocks

import (
	gomock "github.com/golang/mock/gomock"
	domain "github.com/teleclimber/DropServer/cmd/ds-host/domain"
	reflect "reflect"
)

// MockManageUsers is a mock of ManageUsers interface
type MockManageUsers struct {
	ctrl     *gomock.Controller
	recorder *MockManageUsersMockRecorder
}

// MockManageUsersMockRecorder is the mock recorder for MockManageUsers
type MockManageUsersMockRecorder struct {
	mock *MockManageUsers
}

// NewMockManageUsers creates a new mock instance
func NewMockManageUsers(ctrl *gomock.Controller) *MockManageUsers {
	mock := &MockManageUsers{ctrl: ctrl}
	mock.recorder = &MockManageUsersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockManageUsers) EXPECT() *MockManageUsersMockRecorder {
	return m.recorder
}

// AppspacesForUser mocks base method
func (m *MockManageUsers) AppspacesForUser(arg0 domain.UserID) ([]domain.AppspaceUserIDs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppspacesForUser", arg0)
	ret0, _ := ret[0].([]domain.AppspaceUserIDs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AppspacesForUser indicates an expected call of AppspacesForUser
func (mr *MockManageUsersMockRecorder) AppspacesForUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppspacesForUser", reflect.TypeOf((*MockManageUsers)(nil).AppspacesForUser), arg0)
}

// InstanceUser mocks base method
func (m *MockManageUsers) InstanceUser(arg0 domain.AppspaceID, arg1 domain.UserID) (domain.ProxyID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstanceUser", arg0, arg1)
	ret0, _ := ret[0].(domain.ProxyID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InstanceUser indicates an expected call of InstanceUser
func (mr *MockManageUsersMockRecorder) InstanceUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstanceUser", reflect.TypeOf((*MockManageUsers)(nil).InstanceUser), arg0, arg1)
}
