// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/teleclimber/DropServer/cmd/ds-host/testmocks (interfaces: ManageUsers,AppspaceUsersCache,DeleteAppspace)

// Package testmocks is a generated GoMock package.
package testmocks

import (
	gomock "github.com/golang/mock/gomock"
	domain "github.com/teleclimber/DropServer/cmd/ds-host/domain"
	reflect "reflect"
)

// MockManageUsers is a mock of ManageUsers interface
type MockManageUsers struct {
	ctrl     *gomock.Controller
	recorder *MockManageUsersMockRecorder
}

// MockManageUsersMockRecorder is the mock recorder for MockManageUsers
type MockManageUsersMockRecorder struct {
	mock *MockManageUsers
}

// NewMockManageUsers creates a new mock instance
func NewMockManageUsers(ctrl *gomock.Controller) *MockManageUsers {
	mock := &MockManageUsers{ctrl: ctrl}
	mock.recorder = &MockManageUsersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockManageUsers) EXPECT() *MockManageUsersMockRecorder {
	return m.recorder
}

// AppspacesForUser mocks base method
func (m *MockManageUsers) AppspacesForUser(arg0 domain.UserID) (map[domain.AppspaceID]domain.UserIDProxyIDConflicts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppspacesForUser", arg0)
	ret0, _ := ret[0].(map[domain.AppspaceID]domain.UserIDProxyIDConflicts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AppspacesForUser indicates an expected call of AppspacesForUser
func (mr *MockManageUsersMockRecorder) AppspacesForUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppspacesForUser", reflect.TypeOf((*MockManageUsers)(nil).AppspacesForUser), arg0)
}

// GetConflictsForUserID mocks base method
func (m *MockManageUsers) GetConflictsForUserID(arg0 domain.AppspaceID, arg1 domain.UserID) (domain.UserIDProxyIDConflicts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConflictsForUserID", arg0, arg1)
	ret0, _ := ret[0].(domain.UserIDProxyIDConflicts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConflictsForUserID indicates an expected call of GetConflictsForUserID
func (mr *MockManageUsersMockRecorder) GetConflictsForUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConflictsForUserID", reflect.TypeOf((*MockManageUsers)(nil).GetConflictsForUserID), arg0, arg1)
}

// GetProxyIDForUserID mocks base method
func (m *MockManageUsers) GetProxyIDForUserID(arg0 domain.AppspaceID, arg1 domain.UserID) (domain.ProxyID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProxyIDForUserID", arg0, arg1)
	ret0, _ := ret[0].(domain.ProxyID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProxyIDForUserID indicates an expected call of GetProxyIDForUserID
func (mr *MockManageUsersMockRecorder) GetProxyIDForUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProxyIDForUserID", reflect.TypeOf((*MockManageUsers)(nil).GetProxyIDForUserID), arg0, arg1)
}

// UserInAppspace mocks base method
func (m *MockManageUsers) UserInAppspace(arg0 domain.UserID, arg1 []domain.AppspaceUserAuthBare, arg2 domain.AppspaceID) (domain.UserIDProxyIDConflicts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserInAppspace", arg0, arg1, arg2)
	ret0, _ := ret[0].(domain.UserIDProxyIDConflicts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserInAppspace indicates an expected call of UserInAppspace
func (mr *MockManageUsersMockRecorder) UserInAppspace(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserInAppspace", reflect.TypeOf((*MockManageUsers)(nil).UserInAppspace), arg0, arg1, arg2)
}

// UsersForAppspace mocks base method
func (m *MockManageUsers) UsersForAppspace(arg0 domain.AppspaceID) (map[domain.UserID]domain.UserIDProxyIDConflicts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UsersForAppspace", arg0)
	ret0, _ := ret[0].(map[domain.UserID]domain.UserIDProxyIDConflicts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UsersForAppspace indicates an expected call of UsersForAppspace
func (mr *MockManageUsersMockRecorder) UsersForAppspace(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UsersForAppspace", reflect.TypeOf((*MockManageUsers)(nil).UsersForAppspace), arg0)
}

// MockAppspaceUsersCache is a mock of AppspaceUsersCache interface
type MockAppspaceUsersCache struct {
	ctrl     *gomock.Controller
	recorder *MockAppspaceUsersCacheMockRecorder
}

// MockAppspaceUsersCacheMockRecorder is the mock recorder for MockAppspaceUsersCache
type MockAppspaceUsersCacheMockRecorder struct {
	mock *MockAppspaceUsersCache
}

// NewMockAppspaceUsersCache creates a new mock instance
func NewMockAppspaceUsersCache(ctrl *gomock.Controller) *MockAppspaceUsersCache {
	mock := &MockAppspaceUsersCache{ctrl: ctrl}
	mock.recorder = &MockAppspaceUsersCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAppspaceUsersCache) EXPECT() *MockAppspaceUsersCacheMockRecorder {
	return m.recorder
}

// AppspacesForUser mocks base method
func (m *MockAppspaceUsersCache) AppspacesForUser(arg0 domain.UserID) (map[domain.AppspaceID]domain.UserIDProxyIDConflicts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppspacesForUser", arg0)
	ret0, _ := ret[0].(map[domain.AppspaceID]domain.UserIDProxyIDConflicts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AppspacesForUser indicates an expected call of AppspacesForUser
func (mr *MockAppspaceUsersCacheMockRecorder) AppspacesForUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppspacesForUser", reflect.TypeOf((*MockAppspaceUsersCache)(nil).AppspacesForUser), arg0)
}

// UsersForAppspace mocks base method
func (m *MockAppspaceUsersCache) UsersForAppspace(arg0 domain.AppspaceID) (map[domain.UserID]domain.UserIDProxyIDConflicts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UsersForAppspace", arg0)
	ret0, _ := ret[0].(map[domain.UserID]domain.UserIDProxyIDConflicts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UsersForAppspace indicates an expected call of UsersForAppspace
func (mr *MockAppspaceUsersCacheMockRecorder) UsersForAppspace(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UsersForAppspace", reflect.TypeOf((*MockAppspaceUsersCache)(nil).UsersForAppspace), arg0)
}

// MockDeleteAppspace is a mock of DeleteAppspace interface
type MockDeleteAppspace struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteAppspaceMockRecorder
}

// MockDeleteAppspaceMockRecorder is the mock recorder for MockDeleteAppspace
type MockDeleteAppspaceMockRecorder struct {
	mock *MockDeleteAppspace
}

// NewMockDeleteAppspace creates a new mock instance
func NewMockDeleteAppspace(ctrl *gomock.Controller) *MockDeleteAppspace {
	mock := &MockDeleteAppspace{ctrl: ctrl}
	mock.recorder = &MockDeleteAppspaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDeleteAppspace) EXPECT() *MockDeleteAppspaceMockRecorder {
	return m.recorder
}

// Delete mocks base method
func (m *MockDeleteAppspace) Delete(arg0 domain.Appspace) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockDeleteAppspaceMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeleteAppspace)(nil).Delete), arg0)
}
