// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/teleclimber/DropServer/cmd/ds-host/testmocks (interfaces: Authenticator,V0TokenManager)

// Package testmocks is a generated GoMock package.
package testmocks

import (
	gomock "github.com/golang/mock/gomock"
	domain "github.com/teleclimber/DropServer/cmd/ds-host/domain"
	http "net/http"
	reflect "reflect"
)

// MockAuthenticator is a mock of Authenticator interface
type MockAuthenticator struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticatorMockRecorder
}

// MockAuthenticatorMockRecorder is the mock recorder for MockAuthenticator
type MockAuthenticatorMockRecorder struct {
	mock *MockAuthenticator
}

// NewMockAuthenticator creates a new mock instance
func NewMockAuthenticator(ctrl *gomock.Controller) *MockAuthenticator {
	mock := &MockAuthenticator{ctrl: ctrl}
	mock.recorder = &MockAuthenticatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAuthenticator) EXPECT() *MockAuthenticatorMockRecorder {
	return m.recorder
}

// AppspaceUserProxyID mocks base method
func (m *MockAuthenticator) AppspaceUserProxyID(arg0 http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppspaceUserProxyID", arg0)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// AppspaceUserProxyID indicates an expected call of AppspaceUserProxyID
func (mr *MockAuthenticatorMockRecorder) AppspaceUserProxyID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppspaceUserProxyID", reflect.TypeOf((*MockAuthenticator)(nil).AppspaceUserProxyID), arg0)
}

// SetForAccount mocks base method
func (m *MockAuthenticator) SetForAccount(arg0 http.ResponseWriter, arg1 domain.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetForAccount", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetForAccount indicates an expected call of SetForAccount
func (mr *MockAuthenticatorMockRecorder) SetForAccount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetForAccount", reflect.TypeOf((*MockAuthenticator)(nil).SetForAccount), arg0, arg1)
}

// SetForAppspace mocks base method
func (m *MockAuthenticator) SetForAppspace(arg0 http.ResponseWriter, arg1 domain.ProxyID, arg2 domain.AppspaceID, arg3 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetForAppspace", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetForAppspace indicates an expected call of SetForAppspace
func (mr *MockAuthenticatorMockRecorder) SetForAppspace(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetForAppspace", reflect.TypeOf((*MockAuthenticator)(nil).SetForAppspace), arg0, arg1, arg2, arg3)
}

// Unset mocks base method
func (m *MockAuthenticator) Unset(arg0 http.ResponseWriter, arg1 *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unset", arg0, arg1)
}

// Unset indicates an expected call of Unset
func (mr *MockAuthenticatorMockRecorder) Unset(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unset", reflect.TypeOf((*MockAuthenticator)(nil).Unset), arg0, arg1)
}

// MockV0TokenManager is a mock of V0TokenManager interface
type MockV0TokenManager struct {
	ctrl     *gomock.Controller
	recorder *MockV0TokenManagerMockRecorder
}

// MockV0TokenManagerMockRecorder is the mock recorder for MockV0TokenManager
type MockV0TokenManagerMockRecorder struct {
	mock *MockV0TokenManager
}

// NewMockV0TokenManager creates a new mock instance
func NewMockV0TokenManager(ctrl *gomock.Controller) *MockV0TokenManager {
	mock := &MockV0TokenManager{ctrl: ctrl}
	mock.recorder = &MockV0TokenManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockV0TokenManager) EXPECT() *MockV0TokenManagerMockRecorder {
	return m.recorder
}

// CheckToken mocks base method
func (m *MockV0TokenManager) CheckToken(arg0 domain.AppspaceID, arg1 string) (domain.V0AppspaceLoginToken, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckToken", arg0, arg1)
	ret0, _ := ret[0].(domain.V0AppspaceLoginToken)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// CheckToken indicates an expected call of CheckToken
func (mr *MockV0TokenManagerMockRecorder) CheckToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckToken", reflect.TypeOf((*MockV0TokenManager)(nil).CheckToken), arg0, arg1)
}

// GetForProxyID mocks base method
func (m *MockV0TokenManager) GetForProxyID(arg0 domain.AppspaceID, arg1 domain.ProxyID) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForProxyID", arg0, arg1)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetForProxyID indicates an expected call of GetForProxyID
func (mr *MockV0TokenManagerMockRecorder) GetForProxyID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForProxyID", reflect.TypeOf((*MockV0TokenManager)(nil).GetForProxyID), arg0, arg1)
}
