// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/teleclimber/DropServer/cmd/ds-host/testmocks (interfaces: AppspaceFilesEvents,AppspaceTSNetModelEvents,AppUrlDataEvents,AppspaceStatusEvents,InstanceUserAuthsChangeEvents,AppspaceUsersChangeEvents,UserAppspacesEvent)

// Package testmocks is a generated GoMock package.
package testmocks

import (
	gomock "github.com/golang/mock/gomock"
	domain "github.com/teleclimber/DropServer/cmd/ds-host/domain"
	reflect "reflect"
)

// MockAppspaceFilesEvents is a mock of AppspaceFilesEvents interface
type MockAppspaceFilesEvents struct {
	ctrl     *gomock.Controller
	recorder *MockAppspaceFilesEventsMockRecorder
}

// MockAppspaceFilesEventsMockRecorder is the mock recorder for MockAppspaceFilesEvents
type MockAppspaceFilesEventsMockRecorder struct {
	mock *MockAppspaceFilesEvents
}

// NewMockAppspaceFilesEvents creates a new mock instance
func NewMockAppspaceFilesEvents(ctrl *gomock.Controller) *MockAppspaceFilesEvents {
	mock := &MockAppspaceFilesEvents{ctrl: ctrl}
	mock.recorder = &MockAppspaceFilesEventsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAppspaceFilesEvents) EXPECT() *MockAppspaceFilesEventsMockRecorder {
	return m.recorder
}

// Send mocks base method
func (m *MockAppspaceFilesEvents) Send(arg0 domain.AppspaceID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Send", arg0)
}

// Send indicates an expected call of Send
func (mr *MockAppspaceFilesEventsMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockAppspaceFilesEvents)(nil).Send), arg0)
}

// Subscribe mocks base method
func (m *MockAppspaceFilesEvents) Subscribe() <-chan domain.AppspaceID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe")
	ret0, _ := ret[0].(<-chan domain.AppspaceID)
	return ret0
}

// Subscribe indicates an expected call of Subscribe
func (mr *MockAppspaceFilesEventsMockRecorder) Subscribe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockAppspaceFilesEvents)(nil).Subscribe))
}

// SubscribeApp mocks base method
func (m *MockAppspaceFilesEvents) SubscribeApp(arg0 domain.AppID) <-chan domain.AppspaceID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeApp", arg0)
	ret0, _ := ret[0].(<-chan domain.AppspaceID)
	return ret0
}

// SubscribeApp indicates an expected call of SubscribeApp
func (mr *MockAppspaceFilesEventsMockRecorder) SubscribeApp(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeApp", reflect.TypeOf((*MockAppspaceFilesEvents)(nil).SubscribeApp), arg0)
}

// SubscribeOwner mocks base method
func (m *MockAppspaceFilesEvents) SubscribeOwner(arg0 domain.UserID) <-chan domain.AppspaceID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeOwner", arg0)
	ret0, _ := ret[0].(<-chan domain.AppspaceID)
	return ret0
}

// SubscribeOwner indicates an expected call of SubscribeOwner
func (mr *MockAppspaceFilesEventsMockRecorder) SubscribeOwner(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeOwner", reflect.TypeOf((*MockAppspaceFilesEvents)(nil).SubscribeOwner), arg0)
}

// Unsubscribe mocks base method
func (m *MockAppspaceFilesEvents) Unsubscribe(arg0 <-chan domain.AppspaceID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unsubscribe", arg0)
}

// Unsubscribe indicates an expected call of Unsubscribe
func (mr *MockAppspaceFilesEventsMockRecorder) Unsubscribe(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockAppspaceFilesEvents)(nil).Unsubscribe), arg0)
}

// MockAppspaceTSNetModelEvents is a mock of AppspaceTSNetModelEvents interface
type MockAppspaceTSNetModelEvents struct {
	ctrl     *gomock.Controller
	recorder *MockAppspaceTSNetModelEventsMockRecorder
}

// MockAppspaceTSNetModelEventsMockRecorder is the mock recorder for MockAppspaceTSNetModelEvents
type MockAppspaceTSNetModelEventsMockRecorder struct {
	mock *MockAppspaceTSNetModelEvents
}

// NewMockAppspaceTSNetModelEvents creates a new mock instance
func NewMockAppspaceTSNetModelEvents(ctrl *gomock.Controller) *MockAppspaceTSNetModelEvents {
	mock := &MockAppspaceTSNetModelEvents{ctrl: ctrl}
	mock.recorder = &MockAppspaceTSNetModelEventsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAppspaceTSNetModelEvents) EXPECT() *MockAppspaceTSNetModelEventsMockRecorder {
	return m.recorder
}

// Send mocks base method
func (m *MockAppspaceTSNetModelEvents) Send(arg0 domain.AppspaceTSNetModelEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Send", arg0)
}

// Send indicates an expected call of Send
func (mr *MockAppspaceTSNetModelEventsMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockAppspaceTSNetModelEvents)(nil).Send), arg0)
}

// Subscribe mocks base method
func (m *MockAppspaceTSNetModelEvents) Subscribe() <-chan domain.AppspaceTSNetModelEvent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe")
	ret0, _ := ret[0].(<-chan domain.AppspaceTSNetModelEvent)
	return ret0
}

// Subscribe indicates an expected call of Subscribe
func (mr *MockAppspaceTSNetModelEventsMockRecorder) Subscribe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockAppspaceTSNetModelEvents)(nil).Subscribe))
}

// SubscribeApp mocks base method
func (m *MockAppspaceTSNetModelEvents) SubscribeApp(arg0 domain.AppID) <-chan domain.AppspaceTSNetModelEvent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeApp", arg0)
	ret0, _ := ret[0].(<-chan domain.AppspaceTSNetModelEvent)
	return ret0
}

// SubscribeApp indicates an expected call of SubscribeApp
func (mr *MockAppspaceTSNetModelEventsMockRecorder) SubscribeApp(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeApp", reflect.TypeOf((*MockAppspaceTSNetModelEvents)(nil).SubscribeApp), arg0)
}

// SubscribeOwner mocks base method
func (m *MockAppspaceTSNetModelEvents) SubscribeOwner(arg0 domain.UserID) <-chan domain.AppspaceTSNetModelEvent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeOwner", arg0)
	ret0, _ := ret[0].(<-chan domain.AppspaceTSNetModelEvent)
	return ret0
}

// SubscribeOwner indicates an expected call of SubscribeOwner
func (mr *MockAppspaceTSNetModelEventsMockRecorder) SubscribeOwner(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeOwner", reflect.TypeOf((*MockAppspaceTSNetModelEvents)(nil).SubscribeOwner), arg0)
}

// Unsubscribe mocks base method
func (m *MockAppspaceTSNetModelEvents) Unsubscribe(arg0 <-chan domain.AppspaceTSNetModelEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unsubscribe", arg0)
}

// Unsubscribe indicates an expected call of Unsubscribe
func (mr *MockAppspaceTSNetModelEventsMockRecorder) Unsubscribe(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockAppspaceTSNetModelEvents)(nil).Unsubscribe), arg0)
}

// MockAppUrlDataEvents is a mock of AppUrlDataEvents interface
type MockAppUrlDataEvents struct {
	ctrl     *gomock.Controller
	recorder *MockAppUrlDataEventsMockRecorder
}

// MockAppUrlDataEventsMockRecorder is the mock recorder for MockAppUrlDataEvents
type MockAppUrlDataEventsMockRecorder struct {
	mock *MockAppUrlDataEvents
}

// NewMockAppUrlDataEvents creates a new mock instance
func NewMockAppUrlDataEvents(ctrl *gomock.Controller) *MockAppUrlDataEvents {
	mock := &MockAppUrlDataEvents{ctrl: ctrl}
	mock.recorder = &MockAppUrlDataEventsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAppUrlDataEvents) EXPECT() *MockAppUrlDataEventsMockRecorder {
	return m.recorder
}

// Send mocks base method
func (m *MockAppUrlDataEvents) Send(arg0 domain.UserID, arg1 domain.AppURLData) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Send", arg0, arg1)
}

// Send indicates an expected call of Send
func (mr *MockAppUrlDataEventsMockRecorder) Send(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockAppUrlDataEvents)(nil).Send), arg0, arg1)
}

// Subscribe mocks base method
func (m *MockAppUrlDataEvents) Subscribe() <-chan domain.AppURLData {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe")
	ret0, _ := ret[0].(<-chan domain.AppURLData)
	return ret0
}

// Subscribe indicates an expected call of Subscribe
func (mr *MockAppUrlDataEventsMockRecorder) Subscribe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockAppUrlDataEvents)(nil).Subscribe))
}

// SubscribeApp mocks base method
func (m *MockAppUrlDataEvents) SubscribeApp(arg0 domain.AppID) <-chan domain.AppURLData {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeApp", arg0)
	ret0, _ := ret[0].(<-chan domain.AppURLData)
	return ret0
}

// SubscribeApp indicates an expected call of SubscribeApp
func (mr *MockAppUrlDataEventsMockRecorder) SubscribeApp(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeApp", reflect.TypeOf((*MockAppUrlDataEvents)(nil).SubscribeApp), arg0)
}

// SubscribeOwner mocks base method
func (m *MockAppUrlDataEvents) SubscribeOwner(arg0 domain.UserID) <-chan domain.AppURLData {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeOwner", arg0)
	ret0, _ := ret[0].(<-chan domain.AppURLData)
	return ret0
}

// SubscribeOwner indicates an expected call of SubscribeOwner
func (mr *MockAppUrlDataEventsMockRecorder) SubscribeOwner(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeOwner", reflect.TypeOf((*MockAppUrlDataEvents)(nil).SubscribeOwner), arg0)
}

// Unsubscribe mocks base method
func (m *MockAppUrlDataEvents) Unsubscribe(arg0 <-chan domain.AppURLData) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unsubscribe", arg0)
}

// Unsubscribe indicates an expected call of Unsubscribe
func (mr *MockAppUrlDataEventsMockRecorder) Unsubscribe(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockAppUrlDataEvents)(nil).Unsubscribe), arg0)
}

// MockAppspaceStatusEvents is a mock of AppspaceStatusEvents interface
type MockAppspaceStatusEvents struct {
	ctrl     *gomock.Controller
	recorder *MockAppspaceStatusEventsMockRecorder
}

// MockAppspaceStatusEventsMockRecorder is the mock recorder for MockAppspaceStatusEvents
type MockAppspaceStatusEventsMockRecorder struct {
	mock *MockAppspaceStatusEvents
}

// NewMockAppspaceStatusEvents creates a new mock instance
func NewMockAppspaceStatusEvents(ctrl *gomock.Controller) *MockAppspaceStatusEvents {
	mock := &MockAppspaceStatusEvents{ctrl: ctrl}
	mock.recorder = &MockAppspaceStatusEventsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAppspaceStatusEvents) EXPECT() *MockAppspaceStatusEventsMockRecorder {
	return m.recorder
}

// Send mocks base method
func (m *MockAppspaceStatusEvents) Send(arg0 domain.AppspaceStatusEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Send", arg0)
}

// Send indicates an expected call of Send
func (mr *MockAppspaceStatusEventsMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockAppspaceStatusEvents)(nil).Send), arg0)
}

// Subscribe mocks base method
func (m *MockAppspaceStatusEvents) Subscribe() <-chan domain.AppspaceStatusEvent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe")
	ret0, _ := ret[0].(<-chan domain.AppspaceStatusEvent)
	return ret0
}

// Subscribe indicates an expected call of Subscribe
func (mr *MockAppspaceStatusEventsMockRecorder) Subscribe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockAppspaceStatusEvents)(nil).Subscribe))
}

// SubscribeApp mocks base method
func (m *MockAppspaceStatusEvents) SubscribeApp(arg0 domain.AppID) <-chan domain.AppspaceStatusEvent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeApp", arg0)
	ret0, _ := ret[0].(<-chan domain.AppspaceStatusEvent)
	return ret0
}

// SubscribeApp indicates an expected call of SubscribeApp
func (mr *MockAppspaceStatusEventsMockRecorder) SubscribeApp(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeApp", reflect.TypeOf((*MockAppspaceStatusEvents)(nil).SubscribeApp), arg0)
}

// SubscribeOwner mocks base method
func (m *MockAppspaceStatusEvents) SubscribeOwner(arg0 domain.UserID) <-chan domain.AppspaceStatusEvent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeOwner", arg0)
	ret0, _ := ret[0].(<-chan domain.AppspaceStatusEvent)
	return ret0
}

// SubscribeOwner indicates an expected call of SubscribeOwner
func (mr *MockAppspaceStatusEventsMockRecorder) SubscribeOwner(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeOwner", reflect.TypeOf((*MockAppspaceStatusEvents)(nil).SubscribeOwner), arg0)
}

// Unsubscribe mocks base method
func (m *MockAppspaceStatusEvents) Unsubscribe(arg0 <-chan domain.AppspaceStatusEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unsubscribe", arg0)
}

// Unsubscribe indicates an expected call of Unsubscribe
func (mr *MockAppspaceStatusEventsMockRecorder) Unsubscribe(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockAppspaceStatusEvents)(nil).Unsubscribe), arg0)
}

// MockInstanceUserAuthsChangeEvents is a mock of InstanceUserAuthsChangeEvents interface
type MockInstanceUserAuthsChangeEvents struct {
	ctrl     *gomock.Controller
	recorder *MockInstanceUserAuthsChangeEventsMockRecorder
}

// MockInstanceUserAuthsChangeEventsMockRecorder is the mock recorder for MockInstanceUserAuthsChangeEvents
type MockInstanceUserAuthsChangeEventsMockRecorder struct {
	mock *MockInstanceUserAuthsChangeEvents
}

// NewMockInstanceUserAuthsChangeEvents creates a new mock instance
func NewMockInstanceUserAuthsChangeEvents(ctrl *gomock.Controller) *MockInstanceUserAuthsChangeEvents {
	mock := &MockInstanceUserAuthsChangeEvents{ctrl: ctrl}
	mock.recorder = &MockInstanceUserAuthsChangeEventsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockInstanceUserAuthsChangeEvents) EXPECT() *MockInstanceUserAuthsChangeEventsMockRecorder {
	return m.recorder
}

// Send mocks base method
func (m *MockInstanceUserAuthsChangeEvents) Send(arg0 domain.UserID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Send", arg0)
}

// Send indicates an expected call of Send
func (mr *MockInstanceUserAuthsChangeEventsMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockInstanceUserAuthsChangeEvents)(nil).Send), arg0)
}

// Subscribe mocks base method
func (m *MockInstanceUserAuthsChangeEvents) Subscribe() <-chan domain.UserID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe")
	ret0, _ := ret[0].(<-chan domain.UserID)
	return ret0
}

// Subscribe indicates an expected call of Subscribe
func (mr *MockInstanceUserAuthsChangeEventsMockRecorder) Subscribe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockInstanceUserAuthsChangeEvents)(nil).Subscribe))
}

// Unsubscribe mocks base method
func (m *MockInstanceUserAuthsChangeEvents) Unsubscribe(arg0 <-chan domain.UserID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unsubscribe", arg0)
}

// Unsubscribe indicates an expected call of Unsubscribe
func (mr *MockInstanceUserAuthsChangeEventsMockRecorder) Unsubscribe(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockInstanceUserAuthsChangeEvents)(nil).Unsubscribe), arg0)
}

// MockAppspaceUsersChangeEvents is a mock of AppspaceUsersChangeEvents interface
type MockAppspaceUsersChangeEvents struct {
	ctrl     *gomock.Controller
	recorder *MockAppspaceUsersChangeEventsMockRecorder
}

// MockAppspaceUsersChangeEventsMockRecorder is the mock recorder for MockAppspaceUsersChangeEvents
type MockAppspaceUsersChangeEventsMockRecorder struct {
	mock *MockAppspaceUsersChangeEvents
}

// NewMockAppspaceUsersChangeEvents creates a new mock instance
func NewMockAppspaceUsersChangeEvents(ctrl *gomock.Controller) *MockAppspaceUsersChangeEvents {
	mock := &MockAppspaceUsersChangeEvents{ctrl: ctrl}
	mock.recorder = &MockAppspaceUsersChangeEventsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAppspaceUsersChangeEvents) EXPECT() *MockAppspaceUsersChangeEventsMockRecorder {
	return m.recorder
}

// Send mocks base method
func (m *MockAppspaceUsersChangeEvents) Send(arg0 domain.AppspaceID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Send", arg0)
}

// Send indicates an expected call of Send
func (mr *MockAppspaceUsersChangeEventsMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockAppspaceUsersChangeEvents)(nil).Send), arg0)
}

// Subscribe mocks base method
func (m *MockAppspaceUsersChangeEvents) Subscribe() <-chan domain.AppspaceID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe")
	ret0, _ := ret[0].(<-chan domain.AppspaceID)
	return ret0
}

// Subscribe indicates an expected call of Subscribe
func (mr *MockAppspaceUsersChangeEventsMockRecorder) Subscribe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockAppspaceUsersChangeEvents)(nil).Subscribe))
}

// Unsubscribe mocks base method
func (m *MockAppspaceUsersChangeEvents) Unsubscribe(arg0 <-chan domain.AppspaceID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unsubscribe", arg0)
}

// Unsubscribe indicates an expected call of Unsubscribe
func (mr *MockAppspaceUsersChangeEventsMockRecorder) Unsubscribe(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockAppspaceUsersChangeEvents)(nil).Unsubscribe), arg0)
}

// MockUserAppspacesEvent is a mock of UserAppspacesEvent interface
type MockUserAppspacesEvent struct {
	ctrl     *gomock.Controller
	recorder *MockUserAppspacesEventMockRecorder
}

// MockUserAppspacesEventMockRecorder is the mock recorder for MockUserAppspacesEvent
type MockUserAppspacesEventMockRecorder struct {
	mock *MockUserAppspacesEvent
}

// NewMockUserAppspacesEvent creates a new mock instance
func NewMockUserAppspacesEvent(ctrl *gomock.Controller) *MockUserAppspacesEvent {
	mock := &MockUserAppspacesEvent{ctrl: ctrl}
	mock.recorder = &MockUserAppspacesEventMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUserAppspacesEvent) EXPECT() *MockUserAppspacesEventMockRecorder {
	return m.recorder
}

// Send mocks base method
func (m *MockUserAppspacesEvent) Send(arg0 domain.UserID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Send", arg0)
}

// Send indicates an expected call of Send
func (mr *MockUserAppspacesEventMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockUserAppspacesEvent)(nil).Send), arg0)
}

// SubscribeUser mocks base method
func (m *MockUserAppspacesEvent) SubscribeUser(arg0 domain.UserID) <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeUser", arg0)
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// SubscribeUser indicates an expected call of SubscribeUser
func (mr *MockUserAppspacesEventMockRecorder) SubscribeUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeUser", reflect.TypeOf((*MockUserAppspacesEvent)(nil).SubscribeUser), arg0)
}

// Unsubscribe mocks base method
func (m *MockUserAppspacesEvent) Unsubscribe(arg0 <-chan struct{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unsubscribe", arg0)
}

// Unsubscribe indicates an expected call of Unsubscribe
func (mr *MockUserAppspacesEventMockRecorder) Unsubscribe(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockUserAppspacesEvent)(nil).Unsubscribe), arg0)
}
