// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/teleclimber/DropServer/cmd/ds-host/testmocks (interfaces: AppspacePausedEvents)

// Package testmocks is a generated GoMock package.
package testmocks

import (
	gomock "github.com/golang/mock/gomock"
	domain "github.com/teleclimber/DropServer/cmd/ds-host/domain"
	reflect "reflect"
)

// MockAppspacePausedEvents is a mock of AppspacePausedEvents interface
type MockAppspacePausedEvents struct {
	ctrl     *gomock.Controller
	recorder *MockAppspacePausedEventsMockRecorder
}

// MockAppspacePausedEventsMockRecorder is the mock recorder for MockAppspacePausedEvents
type MockAppspacePausedEventsMockRecorder struct {
	mock *MockAppspacePausedEvents
}

// NewMockAppspacePausedEvents creates a new mock instance
func NewMockAppspacePausedEvents(ctrl *gomock.Controller) *MockAppspacePausedEvents {
	mock := &MockAppspacePausedEvents{ctrl: ctrl}
	mock.recorder = &MockAppspacePausedEventsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAppspacePausedEvents) EXPECT() *MockAppspacePausedEventsMockRecorder {
	return m.recorder
}

// Send mocks base method
func (m *MockAppspacePausedEvents) Send(arg0 domain.AppspaceID, arg1 bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Send", arg0, arg1)
}

// Send indicates an expected call of Send
func (mr *MockAppspacePausedEventsMockRecorder) Send(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockAppspacePausedEvents)(nil).Send), arg0, arg1)
}

// Subscribe mocks base method
func (m *MockAppspacePausedEvents) Subscribe(arg0 chan<- domain.AppspacePausedEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Subscribe", arg0)
}

// Subscribe indicates an expected call of Subscribe
func (mr *MockAppspacePausedEventsMockRecorder) Subscribe(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockAppspacePausedEvents)(nil).Subscribe), arg0)
}

// Unsubscribe mocks base method
func (m *MockAppspacePausedEvents) Unsubscribe(arg0 chan<- domain.AppspacePausedEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unsubscribe", arg0)
}

// Unsubscribe indicates an expected call of Unsubscribe
func (mr *MockAppspacePausedEventsMockRecorder) Unsubscribe(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockAppspacePausedEvents)(nil).Unsubscribe), arg0)
}
