// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/teleclimber/DropServer/cmd/ds-host/testmocks (interfaces: SandboxManager,CGroups)

// Package testmocks is a generated GoMock package.
package testmocks

import (
	gomock "github.com/golang/mock/gomock"
	domain "github.com/teleclimber/DropServer/cmd/ds-host/domain"
	reflect "reflect"
)

// MockSandboxManager is a mock of SandboxManager interface
type MockSandboxManager struct {
	ctrl     *gomock.Controller
	recorder *MockSandboxManagerMockRecorder
}

// MockSandboxManagerMockRecorder is the mock recorder for MockSandboxManager
type MockSandboxManagerMockRecorder struct {
	mock *MockSandboxManager
}

// NewMockSandboxManager creates a new mock instance
func NewMockSandboxManager(ctrl *gomock.Controller) *MockSandboxManager {
	mock := &MockSandboxManager{ctrl: ctrl}
	mock.recorder = &MockSandboxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSandboxManager) EXPECT() *MockSandboxManagerMockRecorder {
	return m.recorder
}

// ForApp mocks base method
func (m *MockSandboxManager) ForApp(arg0 *domain.AppVersion) (domain.SandboxI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForApp", arg0)
	ret0, _ := ret[0].(domain.SandboxI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForApp indicates an expected call of ForApp
func (mr *MockSandboxManagerMockRecorder) ForApp(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForApp", reflect.TypeOf((*MockSandboxManager)(nil).ForApp), arg0)
}

// ForMigration mocks base method
func (m *MockSandboxManager) ForMigration(arg0 domain.AppVersion, arg1 *domain.Appspace) (domain.SandboxI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForMigration", arg0, arg1)
	ret0, _ := ret[0].(domain.SandboxI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForMigration indicates an expected call of ForMigration
func (mr *MockSandboxManagerMockRecorder) ForMigration(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForMigration", reflect.TypeOf((*MockSandboxManager)(nil).ForMigration), arg0, arg1)
}

// GetForAppspace mocks base method
func (m *MockSandboxManager) GetForAppspace(arg0 *domain.AppVersion, arg1 *domain.Appspace) (domain.SandboxI, chan struct{}) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForAppspace", arg0, arg1)
	ret0, _ := ret[0].(domain.SandboxI)
	ret1, _ := ret[1].(chan struct{})
	return ret0, ret1
}

// GetForAppspace indicates an expected call of GetForAppspace
func (mr *MockSandboxManagerMockRecorder) GetForAppspace(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForAppspace", reflect.TypeOf((*MockSandboxManager)(nil).GetForAppspace), arg0, arg1)
}

// StopAppspace mocks base method
func (m *MockSandboxManager) StopAppspace(arg0 domain.AppspaceID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StopAppspace", arg0)
}

// StopAppspace indicates an expected call of StopAppspace
func (mr *MockSandboxManagerMockRecorder) StopAppspace(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopAppspace", reflect.TypeOf((*MockSandboxManager)(nil).StopAppspace), arg0)
}

// MockCGroups is a mock of CGroups interface
type MockCGroups struct {
	ctrl     *gomock.Controller
	recorder *MockCGroupsMockRecorder
}

// MockCGroupsMockRecorder is the mock recorder for MockCGroups
type MockCGroupsMockRecorder struct {
	mock *MockCGroups
}

// NewMockCGroups creates a new mock instance
func NewMockCGroups(ctrl *gomock.Controller) *MockCGroups {
	mock := &MockCGroups{ctrl: ctrl}
	mock.recorder = &MockCGroupsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCGroups) EXPECT() *MockCGroupsMockRecorder {
	return m.recorder
}

// AddPid mocks base method
func (m *MockCGroups) AddPid(arg0 string, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPid", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPid indicates an expected call of AddPid
func (mr *MockCGroupsMockRecorder) AddPid(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPid", reflect.TypeOf((*MockCGroups)(nil).AddPid), arg0, arg1)
}

// CreateCGroup mocks base method
func (m *MockCGroups) CreateCGroup(arg0 domain.CGroupLimits) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCGroup", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCGroup indicates an expected call of CreateCGroup
func (mr *MockCGroupsMockRecorder) CreateCGroup(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCGroup", reflect.TypeOf((*MockCGroups)(nil).CreateCGroup), arg0)
}

// RemoveCGroup mocks base method
func (m *MockCGroups) RemoveCGroup(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCGroup", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveCGroup indicates an expected call of RemoveCGroup
func (mr *MockCGroupsMockRecorder) RemoveCGroup(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCGroup", reflect.TypeOf((*MockCGroups)(nil).RemoveCGroup), arg0)
}
