# We don't test on build because for the time being some of our tests are flaky
# Add tests when we have that under control.

name: Build Dropserver

on: 
  workflow_dispatch:
  workflow_call:

jobs:
  build_common:
    uses: teleclimber/DropServer/.github/workflows/build_common.yml@master

  build_all:
    needs: build_common
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix:
        include:
          - runs_on: ubuntu-24.04
            os: linux
            arch: amd64
          - runs_on: ubuntu-24.04-arm
            os: linux
            arch: arm64
          - runs_on: macos-15-intel
            os: darwin
            arch: amd64
          - runs_on: macos-15
            os: darwin
            arch: arm64

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.24

    # ds-host
    - name: Download frontend-ds-host
      uses: actions/download-artifact@v4
      with:
        name: frontend-ds-host
        path: frontend-ds-host/dist/

    - name: Build ds-host
      run: go build -ldflags="-X main.cmd_version=`git describe --tags --dirty`" -o dist/bin/ds-host ./cmd/ds-host

    - name: Archive ds-host
      run: tar -czf ds-host-${{ matrix.os }}-${{ matrix.arch }}.tar.gz ds-host
      working-directory: dist/bin

    - name: Upload ds-host archive
      uses: actions/upload-artifact@v4
      with:
        name: ds-host-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
        path: dist/bin/ds-host-${{ matrix.os }}-${{ matrix.arch }}.tar.gz

    # ds-dev:
    - name: Download frontend-ds-dev
      uses: actions/download-artifact@v4
      with:
        name: frontend-ds-dev
        path: frontend-ds-dev/dist/
    - name: Build ds-dev
      run: go build -ldflags="-X main.cmd_version=`git describe --tags --dirty`" -o dist/bin/ds-dev ./cmd/ds-dev

    - name: Archive ds-dev
      run: tar -czf ds-dev-${{ matrix.os }}-${{ matrix.arch }}.tar.gz ds-dev
      working-directory: dist/bin

    - name: Upload ds-dev archive
      uses: actions/upload-artifact@v4
      with:
        name: ds-dev-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
        path: dist/bin/ds-dev-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
