name: Release Dropserver

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_all:
    uses: teleclimber/DropServer/.github/workflows/build.yml@master

  release:
    needs: build_all
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Add release dir
      run: mkdir release/
    - name: Release notes
      run: git log $(git tag --list --sort=-version:refname "v*" | head -n 2 | tail -n 1)..HEAD --oneline > release/CHANGELOG.txt

    - uses: actions/download-artifact@v5
      with:
        path: artifacts/
        merge-multiple: true

    - name: Display structure of downloaded files (for debugging)
      run: ls -l artifacts/

    # move files we want to release
    - name: Move ds-dev to release
      run: find artifacts/ -regextype posix-extended -regex '.*ds-dev-(linux|MacOS)-(x86_64|arm64).tar.gz' -exec cp '{}' release/ \;
    - name: Move ds-host to release
      run: find artifacts/ -regextype posix-extended -regex '.*ds-host-linux-(x86_64|arm64).tar.gz' -exec cp '{}' release/ \;

    - name: Display structure of release files (for debugging)
      run: ls -l release/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: release/CHANGELOG.txt
        prerelease: false
        files: release/*
